apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-secret
  
data:
  # FEDEX_grant_type: "client_credentials"
  # FEDEX_rates_grant_type: "client_grant_credentials"
  DB_APIDBConnectionString: "c2VydmVyPXBoYXJtZXRyYWRlLmNsdXN0ZXItYzF6b25xZXl1M21uLnVzLWVhc3QtMS5yZHMuYW1hem9uYXdzLmNvbTt1c2VyPWFkbWluO3Bhc3N3b3JkPWxTYzk2UmxuU0xnb1cxVztkYXRhYmFzZT1waGFybWV0cmFkZWRiO0NvbnZlcnQgWmVybyBEYXRldGltZT1UcnVl"
  AWS_AccessKey: "QUtJQVNRWlE3TTRBRVZWMkdNSDU="
  AWS_SecretKey: "SCsvbGY4T2E3dkhhaFdNS3JxVGJrZlZIMWFzSFBEU0RLcWZvc2dxSA=="
  AWS_BucketName: "cHJvZC1waGFyYW1ldHJhZGU="
  AWS_Region: "dXMtZWFzdC0x"
  AWS_AwsSesAccessKeyId: "QUtJQVNRWlE3TTRBQklNS0JRNzI="
  AWS_AwsSesSecretAccessKey: "NDl4L3N3SWJEQnZ5REp2TnFjUUVLU2JCTmVDclpKaXZJaHNvMkxnOQ=="
  AWS_AwsSesRegionEndPoint: "dXMtZWFzdC0x"
  FEDEX_grant_type: "Y2xpZW50X2NyZWRlbnRpYWxz"
  FEDEX_client_id: "bDcyODQ5NmQyOTY4ODE0MzJhYTdhODQ0MzZjZjY5NGVmZQ=="
  FEDEX_client_secret: "YzVhYTFhZmNmNDNhNDg3OGIwNTFmMTk1NzM3Yjk5NTc="
  FEDEX_rates_grant_type: "Y2xpZW50X2NyZWRlbnRpYWxz"
  FEDEX_rates_client_id: "bDdkYTI4MWY4ODQ3YWY0ZDc2OGJjNWE3ZDNkMWJiMDJlOA=="
  FEDEX_rates_client_secret: "MjQyNmQ3MjBhOTJmNDNjZGJlZjZlMWQ2ZDg3MTczZmE="
  SQUAREUP_access_token: "RUFBQWxxLUQwVnRUR1Bzdy1PV1NkZ2ZHVUU2M0NZbUJKVk16UmlFTGE3ZXlKSHJQYThnNWJsZXliZDRtSmk3Tw=="
  SQUAREUP_Environment: "UFJPRFVDVElPTg=="