apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-secret
  
data:
  # FEDEX_grant_type: "client_credentials"
  # FEDEX_rates_grant_type: "client_grant_credentials"
  FEDEX_client_id: "bDcyODQ5NmQyOTY4ODE0MzJhYTdhODQ0MzZjZjY5NGVmZQ=="
  FEDEX_client_secret: "YzVhYTFhZmNmNDNhNDg3OGIwNTFmMTk1NzM3Yjk5NTc="
  FEDEX_rates_client_id: "bDdkYTI4MWY4ODQ3YWY0ZDc2OGJjNWE3ZDNkMWJiMDJlOA=="
  FEDEX_rates_client_secret: "MjQyNmQ3MjBhOTJmNDNjZGJlZjZlMWQ2ZDg3MTczZmE="