apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
  labels:
    app: api-gateway
spec:
  ports:
    - port: 80
      targetPort: 5000
  selector:
    app: api-gateway
  type: ClusterIP